quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${SUPABASE_URL}
quarkus.datasource.username=${SUPABASE_USER}
quarkus.datasource.password=${SUPABASE_PASSWORD}
quarkus.hibernate-orm.database.generation=update

mp.jwt.verify.issuer=https://ifiavytwfeovpricwlaa.supabase.co
mp.jwt.verify.publickey.location=https://ifiavytwfeovpricwlaa.supabase.co/sb_publishable_0LoCObHSP_odC4o-CLVp5A_ued--GwV
quarkus.http.cors=true

quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization